# https://github.com/marketplace/actions/release-drafter#configuration
name-template: '$RESOLVED_VERSION CI'
tag-template: 'v$RESOLVED_VERSION'
version-resolver:
  major:
    labels:
      - 'Version/Major'
  minor:
    labels:
      - 'Version/Minor'
  patch:
    labels:
      - 'Version/Patch'
  default: patch
exclude-labels:
  - 'Version/None'
prerelease: true
template: |
  <!--Example release name: $RESOLVED_VERSION xxx Update [Alpha|Beta]-->
  <!--Please release immediately after modifying as any changes will be overwritten on next run of the Test workflow-->

  ## Changes from $PREVIOUS_TAG (Recently merged first)
  $CHANGES
  
  ## Contributors
  $CONTRIBUTORS
categories:
  - title: '🌈 New Platform!'
    labels:
      - 'Type/Platform'
  - title: '🚀 Features'
    labels:
      - 'Type/Enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'Type/Bug'
  - title: '🧰 Maintenance'
    label: 'Type/Housekeeping'
# Extra line before $BODY or markdown on the first line of $BODY will be interpreted as plain text
change-template: |
  <details><summary>$TITLE (#$NUMBER) @$AUTHOR</summary>
  
  $BODY
  </details>
no-changes-template: '* (No changes)'
replacers:
  # We don't support nested <summary> and <details> so we add a (?!<details>|<summary>)
  - search: '/<details><summary>((?:(?!<details>|<summary>).)+?)<\/summary>\s*<\/details>/g'
    replace: '- $1'
